id: P000504
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1GS60395
  title: མན་ངག་རྫོགས་པ་ཆེན་པོའི་གནད་ཐོར་བུ
  author: ''
  volumes:
    faa3ed6692184333936f334edcf7f73a:
      image_group_id: I1GS60397
      title: Volume 1 of man ngag rdzogs pa chen po'i gnad thor bu
      volume_number: 1
      total_pages: 404
      base_file: v001.txt
